name: Deploy Frontend

on:
  push:
    branches:
      - main  # Trigger on 'staging' branch
    paths:
      - "**"  # Monitor changes in the entire repository
      - ".github/workflows/deploy.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            # Navigate to the app directory on the server
            cd /var/www/bo/interavia-react

            # Pull the latest changes from the staging branch
            git pull origin main

            # Build and deploy the frontend container
            docker-compose build frontend
            docker-compose up -d frontend
          EOF
